<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elmah.Io.BlazorWebApp.Example.Net10.Client\Elmah.Io.BlazorWebApp.Example.Net10.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.11" />
    <PackageReference Include="Elmah.Io.Extensions.Logging" Version="6.0.79-pre" />
    <PackageReference Include="Elmah.Io.AspNetCore.ExtensionsLogging" Version="6.0.79-pre" />
  </ItemGroup>

</Project>
